meta_title: "Allergo Scan"
meta_description: "Easily control your food allergies with Allergo. Scan the products, get immediate confirmation on their allergens based on your profile, be alerted of any recipe changes."
meta_image: "logo.png" # Une image dans votre dossier app/assets/images/
# twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards
